# Version
version: '3.1'

# Setup
services:

  # WordPress
  wordpress:
    depends_on:
      - db
    image: phpdocker
    restart: always
    ports:
      - 80:80
      - 3080:80
    volumes:
      - ./development:/var/www/html

  # PHPMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db

  # MySQL
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

# Volumes
volumes:
  wordpress_db:
  wordpress_uploads: